### PR TITLE
Fix error 'associated item not found in u64'

### PR DESCRIPTION
**Pull request by perronet**
It wasn't compiling because of this

### CODE REVIEW

**Comment by nanpuyue** [comment]
`max_value()` is soft-deprecated.

You should use a newer toolchains (>= 1.43.0).

**Comment by symphorien** [comment]
well the readme states that rustc 1.36+ is supported but it does not compile with 1.41.

**Comment by XuShaohua** [comment]
In [libcore/num/mod.rs](https://doc.rust-lang.org/src/core/num/mod.rs.html#4484), max_value() is defined as:

```rust
#[inline]
fn max_value() -> Self { Self::MAX }
```

CC @perronet

**Comment by XuShaohua** [comment]
For rustc-1.41.0, try to redeclare `u64` type in head of `prctl.rs` file by adding:
```rust
use core::u64;
```
Thus, `u64::MAX` type attribute shall be available again. And it's better to use `MAX` instead of `max_value()` method as it has been marked as soft_deprecated.
@perronet Please consider updating this patch and pull again.

**Comment by perronet** [comment]
Actually in the end I solved this problem by simply updating the toolchain.

> Please consider updating this patch and pull again.

Sure, I'll rollback to the previous version of the toolchain to test if this patch works and then I'll submit another pull request.

**Comment by perronet** [comment]
Seems to be working fine, you can merge :+1:

**Comment by XuShaohua** [comment]
If there is no more issue, a new minor version will be released by the end of this week.

**Pull request merged**
